version: '3.1'

services:
  wpcivi:
    image: theikkinen/private-repo:v1
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_PASSWORD: somepassword

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somepassword
