version: "3.3"

services:
  wpcivi:
    build: ../
    restart: always
    ports:
      - 8080:80
    environment:
      SITE_TITLE: Example
      WORDPRESS_DB_PASSWORD: somepassword
      WORDPRESS_BASE_URL: 10.174.52.21:8080
      WORDPRESS_ADMIN_USER: admin
      WORDPRESS_ADMIN_PASSWORD: admin
      WORDPRESS_ADMIN_EMAIL: admin@example.com
  
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somepassword