version: "3.3"

services:
  wpcivi:
    build: ../
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_PASSWORD: somepassword
      WORDPRESS_BASE_URL: 10.174.52.21:8080

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somepassword
